FROM centos:7

ENV TERM=xterm-256color
ENV container=docker

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
COPY scripts/centmin-option-4.sh /home/centmin-option-4.sh
RUN chmod +x /home/centmin-option-4.sh

COPY scripts/centmin-option-5.sh /home/centmin-option-5.sh
RUN chmod +x /home/centmin-option-5.sh

COPY scripts/centmin-option-5-php8.1.sh /home/centmin-option-5-php8.1.sh
RUN chmod +x /home/centmin-option-5-php8.1.sh

COPY scripts/centmin-option-5-php8.2.sh /home/centmin-option-5-php8.2.sh
RUN chmod +x /home/centmin-option-5-php8.2.sh
VOLUME [ "/sys/fs/cgroup", "/run", "/tmp" ]
CMD ["/usr/sbin/init"]
