FROM quay.io/centos/centos:stream9

ENV TERM=xterm-256color
ENV container=docker

RUN dnf clean all && \
    dnf -y update && \
    dnf install -y --skip-broken \
        initscripts \
        systemd-sysv \
        systemd-devel \
        dos2unix \
        python3 \
        iptables   \
        iproute    \
        kmod       \
        procps-ng  \
        sudo       \
        udev &&    \
    # Unmask services
    systemctl unmask                                                  \
        systemd-remount-fs.service                                    \
        dev-hugepages.mount                                           \
        sys-fs-fuse-connections.mount                                 \
        systemd-logind.service                                        \
        getty.target                                                  \
        console-getty.service &&                                      \
    # Prevents journald from reading kernel messages from /dev/kmsg
    echo "ReadKMsg=no" >> /etc/systemd/journald.conf &&               \
                                                                      \
    # Housekeeping
    dnf clean all &&                                                  \
    rm -rf                                                            \
       /var/cache/dnf/*                                               \
       /var/log/*                                                     \
       /tmp/*                                                         \
       /var/tmp/*                                                     \
       /usr/share/doc/*                                               \
       /usr/share/man/*

RUN systemctl mask systemd-journald-audit.socket systemd-udev-trigger.service systemd-firstboot.service systemd-networkd-wait-online.service

RUN mkdir -p /usr/src/kernels /usr/share/sysbench
RUN mkdir -p /var/lib/pgsql/16/data/
RUN chmod 0700 /var/lib/pgsql/16/data/
RUN chown postgres:postgres /var/lib/pgsql/16/data/

COPY scripts/openssltest.sh /home/openssltest.sh
RUN chmod +x /home/openssltest.sh

COPY scripts/sysbench-run.sh /home/sysbench-run.sh
RUN chmod +x /home/sysbench-run.sh

COPY scripts/mariadb-ssl-setup.sh /home/mariadb-ssl-setup.sh
RUN chmod +x /home/mariadb-ssl-setup.sh

COPY scripts/centmin-option-4.sh /home/centmin-option-4.sh
RUN chmod +x /home/centmin-option-4.sh

COPY scripts/centmin-option-4-master.sh /home/centmin-option-4-master.sh
RUN chmod +x /home/centmin-option-4-master.sh

COPY scripts/centmin-option-5.sh /home/centmin-option-5.sh
RUN chmod +x /home/centmin-option-5.sh

COPY scripts/centmin-option-5-php7.3.sh /home/centmin-option-5-php7.3.sh
RUN chmod +x /home/centmin-option-5-php7.3.sh

COPY scripts/centmin-option-5-php7.4.sh /home/centmin-option-5-php7.4.sh
RUN chmod +x /home/centmin-option-5-php7.4.sh

COPY scripts/centmin-option-5-php8.1.sh /home/centmin-option-5-php8.1.sh
RUN chmod +x /home/centmin-option-5-php8.1.sh

COPY scripts/centmin-option-5-php8.2.sh /home/centmin-option-5-php8.2.sh
RUN chmod +x /home/centmin-option-5-php8.2.sh

COPY scripts/centmin-option-5-php8.3.sh /home/centmin-option-5-php8.3.sh
RUN chmod +x /home/centmin-option-5-php8.3.sh

VOLUME [ "/sys/fs/cgroup", "/run" ]
CMD ["/sbin/init"]
