FROM centos:7

ENV TERM=xterm-256color
ENV container=docker

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

RUN mkdir -p /var/run/postgresql
RUN mkdir -p /usr/src/kernels
RUN mkdir -p /var/lib/pgsql/16/data/
RUN chmod 0700 /var/lib/pgsql/16/data/
RUN chown postgres:postgres /var/lib/pgsql/16/data/
RUN chown postgres:postgres /var/run/postgresql


COPY scripts/centmin-option-11-submenu-0-y.sh /home/centmin-option-11-submenu-0-y.sh
RUN chmod +x /home/centmin-option-11-submenu-0-y.sh

COPY scripts/centmin-option-11-submenu-0-n.sh /home/centmin-option-11-submenu-0-n.sh
RUN chmod +x /home/centmin-option-11-submenu-0-n.sh

COPY scripts/phpbench.sh /home/phpbench.sh
RUN chmod +x /home/phpbench.sh

COPY scripts/bench.php /home/bench.php
RUN chmod +x /home/bench.php

COPY scripts/micro_bench.php /home/micro_bench.php
RUN chmod +x /home/micro_bench.php

COPY scripts/detailed_benchmark.php /home/detailed_benchmark.php
RUN chmod +x /home/detailed_benchmark.php

COPY scripts/openssltest.sh /home/openssltest.sh
RUN chmod +x /home/openssltest.sh

COPY scripts/sysbench-run.sh /home/sysbench-run.sh
RUN chmod +x /home/sysbench-run.sh

COPY scripts/mariadb-ssl-setup.sh /home/mariadb-ssl-setup.sh
RUN chmod +x /home/mariadb-ssl-setup.sh

COPY scripts/centmin-option-4.sh /home/centmin-option-4.sh
RUN chmod +x /home/centmin-option-4.sh

COPY scripts/centmin-option-4-master.sh /home/centmin-option-4-master.sh
RUN chmod +x /home/centmin-option-4-master.sh

COPY scripts/centmin-option-5.sh /home/centmin-option-5.sh
RUN chmod +x /home/centmin-option-5.sh

COPY scripts/centmin-option-5-php7.3.sh /home/centmin-option-5-php7.3.sh
RUN chmod +x /home/centmin-option-5-php7.3.sh

COPY scripts/centmin-option-5-php7.4.sh /home/centmin-option-5-php7.4.sh
RUN chmod +x /home/centmin-option-5-php7.4.sh

COPY scripts/centmin-option-5-php8.1.sh /home/centmin-option-5-php8.1.sh
RUN chmod +x /home/centmin-option-5-php8.1.sh

COPY scripts/centmin-option-5-php8.2.sh /home/centmin-option-5-php8.2.sh
RUN chmod +x /home/centmin-option-5-php8.2.sh

COPY scripts/centmin-option-5-php8.3.sh /home/centmin-option-5-php8.3.sh
RUN chmod +x /home/centmin-option-5-php8.3.sh
VOLUME [ "/sys/fs/cgroup", "/run", "/tmp" ]
CMD ["/usr/sbin/init"]
