FROM almalinux/9-init

ENV TERM=xterm-256color
ENV container=docker

RUN dnf clean all && \
    dnf -y update && \
    dnf install -y \
        initscripts \
        systemd-sysv \
        dos2unix \
        python3 \
        iptables   \
        iproute    \
        kmod       \
        procps-ng  \
        sudo       \
        udev &&    \
    # Unmask services
    systemctl unmask                                                  \
        systemd-remount-fs.service                                    \
        dev-hugepages.mount                                           \
        sys-fs-fuse-connections.mount                                 \
        systemd-logind.service                                        \
        getty.target                                                  \
        console-getty.service &&                                      \
    # Prevents journald from reading kernel messages from /dev/kmsg
    echo "ReadKMsg=no" >> /etc/systemd/journald.conf &&               \
                                                                      \
    # Housekeeping
    dnf clean all &&                                                  \
    rm -rf                                                            \
       /var/cache/dnf/*                                               \
       /var/log/*                                                     \
       /tmp/*                                                         \
       /var/tmp/*                                                     \
       /usr/share/doc/*                                               \
       /usr/share/man/*

RUN systemctl mask systemd-journald-audit.socket systemd-udev-trigger.service systemd-firstboot.service systemd-networkd-wait-online.service

COPY scripts/centmin-option-4.sh /home/centmin-option-4.sh
RUN chmod +x /home/centmin-option-4.sh

COPY scripts/centmin-option-5.sh /home/centmin-option-5.sh
RUN chmod +x /home/centmin-option-5.sh

COPY scripts/centmin-option-5-php8.1.sh /home/centmin-option-5-php8.1.sh
RUN chmod +x /home/centmin-option-5-php8.1.sh

COPY scripts/centmin-option-5-php8.2.sh /home/centmin-option-5-php8.2.sh
RUN chmod +x /home/centmin-option-5-php8.2.sh

VOLUME [ "/sys/fs/cgroup", "/run" ]
CMD ["/sbin/init"]
