name: Cancel Queued Workflows
on:
  workflow_dispatch:
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Queued Workflows
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          #!/bin/bash
          set -e

          # Function to get workflow runs with pagination
          get_workflow_runs() {
            local page=1
            local per_page=100
            local all_runs=""

            while true; do
              local response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/${{ github.repository }}/actions/runs?status=queued&per_page=$per_page&page=$page")
              
              local runs=$(echo "$response" | jq -r '.workflow_runs[].id')
              
              if [ -z "$runs" ]; then
                break
              fi
              
              all_runs+=" $runs"
              page=$((page + 1))
            done

            echo "$all_runs"
          }

          # Get all queued workflow runs
          queued_runs=$(get_workflow_runs)

          # Cancel each queued run
          for run_id in $queued_runs; do
            curl -s -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id/cancel"
            echo "Cancelled queued workflow run $run_id"
          done