name: Cancel Queued Workflows

on:
  workflow_dispatch:

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Cancel Queued Workflows
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          queued_runs=$(gh api -H "Accept: application/vnd.github.v3+json" /repos/${{ github.repository }}/actions/runs?status=queued | jq -r '.workflow_runs[].id')
          for run_id in $queued_runs; do
            gh api -X POST -H "Accept: application/vnd.github.v3+json" /repos/${{ github.repository }}/actions/runs/$run_id/cancel
          done
