name: Cancel In-Progress Workflows
on:
  workflow_dispatch:
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel In-Progress Workflows
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          # Get in-progress workflow runs
          in_progress_runs=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?status=in_progress" \
            | jq -r '.workflow_runs[].id')

          # Cancel each in-progress run
          for run_id in $in_progress_runs; do
            curl -s -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id/cancel"
            echo "Cancelled workflow run $run_id"
          done