name: 0 - Build Official AlmaLinux 10 Image

on:
  workflow_dispatch:

jobs:
  build-qcow2:
    runs-on: ubuntu-24.04
    timeout-minutes: 180  # 3 hour timeout for TCG

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            qemu-system-x86 \
            qemu-utils \
            ovmf \
            cloud-image-utils

      - name: Setup Packer
        uses: hashicorp/setup-packer@v3.1.0
        with:
          version: '1.12.0'

      - name: Download ISO & extract checksum
        run: |
          ISO_URL="https://repo.almalinux.org/almalinux/10/isos/x86_64/AlmaLinux-10-latest-x86_64-minimal.iso"
          ISO_NAME="${ISO_URL##*/}"
          
          # Download ISO
          curl -L -o "$ISO_NAME" "$ISO_URL"
          
          # Get checksum from CHECKSUM file
          curl -sSL "https://repo.almalinux.org/almalinux/10/isos/x86_64/CHECKSUM" -o CHECKSUM
          ISO_CHECKSUM=$(grep "SHA256 (${ISO_NAME})" CHECKSUM | awk '{print $4}')
          
          echo "ISO_NAME=$ISO_NAME" >> $GITHUB_ENV
          echo "ISO_CHECKSUM=$ISO_CHECKSUM" >> $GITHUB_ENV

      - name: Validate Packer template
        run: |
          packer init packer/almalinux10-official.pkr.hcl
          packer validate \
            -var "iso_url=file://${GITHUB_WORKSPACE}/${ISO_NAME}" \
            -var "iso_checksum=${ISO_CHECKSUM}" \
            packer/almalinux10-official.pkr.hcl

      - name: Build QCOW2 with Packer
        env:
          PACKER_LOG: 1
          PACKER_LOG_PATH: packer-build.log
        run: |
          packer build \
            -on-error=abort \
            -var "iso_url=file://${GITHUB_WORKSPACE}/${ISO_NAME}" \
            -var "iso_checksum=${ISO_CHECKSUM}" \
            packer/almalinux10-official.pkr.hcl

      - name: Test the built image
        if: success()
        run: |
          # Quick smoke test of the built image
          QCOW_FILE=$(find build/almalinux10 -name "*.qcow2" -type f)
          echo "Built image: $QCOW_FILE"
          qemu-img info "$QCOW_FILE"
          
          # Optional: Boot test
          timeout 300 qemu-system-x86_64 \
            -m 1024 \
            -nographic \
            -snapshot \
            -drive file="$QCOW_FILE",if=virtio \
            -serial mon:stdio || true

      - name: Upload QCOW2 artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: almalinux-10-gencloud-qcow2
          path: build/almalinux10/*.qcow2
          retention-days: 7

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            packer-build.log
            /tmp/serial.log