name: AlmaLinux 8

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build 
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        load: true
        tags: cmm_el8:latest

    - name: Run container
      run: |
        docker run -d --name=cmm_el8 --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro cmm_el8:latest
        sleep 10  # give it some time to boot
        docker exec -it cmm_el8 curl -4sL https://centminmod.com/installer-el8x.sh | bash ./installer-el8x.sh