name: AlmaLinux 8

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-almalinux-8-workflow]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Sysbox
      run: |
        curl -LO https://downloads.nestybox.com/sysbox/releases/v0.6.2/sysbox-ce_0.6.2-0.linux_amd64.deb
        sudo dpkg -i sysbox-ce_0.6.2-0.linux_amd64.deb || sudo apt-get install -f

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build 
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfiles/Dockerfile-almalinux8
        platforms: linux/amd64
        load: true
        tags: cmm_el8:latest

    - name: Run container Centmmin Mod LEMP AlmaLinux 8 Install
      run: |
        docker run -d --name=cmm_el8 --runtime=sysbox-runc --cap-add=SYS_ADMIN --security-opt seccomp=unconfined --security-opt label=disable --security-opt apparmor=unconfined -v /tmp/$(mktemp -d):/run -v /sys/fs/cgroup:/sys/fs/cgroup:ro cmm_el8:latest
        sleep 10
        docker exec cmm_el8 bash -c "curl -4sL https://centminmod.com/installer-el8x.sh | bash"
      continue-on-error: true

    - name: Inspect PHP-FPM setup
      run: |
        sleep 10
        docker exec cmm_el8 bash -c "systemctl restart php-fpm.service"
        sleep 10
        docker exec cmm_el8 bash -c "journalctl -xe --no-pager | tail -n 500"
        sleep 10
        docker exec cmm_el8 bash -c "systemctl status php-fpm.service"
        sleep 10
        docker exec cmm_el8 bash -c "php-config"
        sleep 10
        docker exec cmm_el8 bash -c "php -v"
      continue-on-error: true

    - name: Inspect Nginx setup
      run: |
        sleep 10
        docker exec cmm_el8 bash -c "ls -lAh /usr/local/nginx/logs"
        sleep 10
        docker exec cmm_el8 bash -c "cat /usr/local/nginx/logs/nginx.pid"
        sleep 10
        docker exec cmm_el8 bash -c "ps aux | grep nginx"
        sleep 10
        docker exec cmm_el8 bash -c "systemctl status nginx.service"
        sleep 10
        docker exec cmm_el8 bash -c "curl -I http://localhost"
        sleep 10
        docker exec cmm_el8 bash -c "nginx -V"
      continue-on-error: true

    - name: Inspect MariaDB setup
      run: |
        sleep 10
        docker exec cmm_el8 bash -c "mysqladmin var | tr -s ' '"
        sleep 10
        docker exec cmm_el8 bash -c "systemctl status mariadb.service"
      continue-on-error: true

    - name: Inspect pure-ftpd setup
      run: |
        sleep 10
        docker exec cmm_el8 bash -c "ls -lAh /etc/systemd/system/pure-ftpd.service.d"
        sleep 10
        docker exec cmm_el8 bash -c "cat /etc/systemd/system/pure-ftpd.service.d/pidfile.conf"
        sleep 10
        docker exec cmm_el8 bash -c "journalctl -u pure-ftpd --no-pager | tail -n 150"
        sleep 10
        docker exec cmm_el8 bash -c "systemctl status pure-ftpd.service"
      continue-on-error: true

    - name: Inspect chronyd setup
      run: |
        sleep 10
        docker exec cmm_el8 bash -c "journalctl -u chronyd --no-pager | tail -n 150"
        sleep 10
        docker exec cmm_el8 bash -c "systemctl status chronyd.service"
      continue-on-error: true

    - name: Inspect Sysstat and systemd-journald service
      run: |
        docker exec cmm_el8 bash -c "systemctl status sysstat.service"
        docker exec cmm_el8 bash -c "systemctl status systemd-journald.service"
      continue-on-error: true
    
    - name: Check permissions of /var/log/journal
      run: |
        docker exec cmm_el8 bash -c "ls -ld /var/log/journal"
      continue-on-error: true
    
    - name: Show recent systemd-journald logs
      run: |
        docker exec cmm_el8 bash -c "journalctl --unit=systemd-journald.service --no-pager | tail -n 500"
      continue-on-error: true
