name: 131.00stable 0 - Manual AlmaLinux vs Rocky Linux vs Oracle Linux EL8/EL9 Workflow

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger almalinux-vs-rockylinux-oracle-linux-8 workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: centminmod/centminmod-workflows
          event-type: run-almalinux-vs-rockylinux-oraclelinux-8-workflow-13100stable
          
      - name: Trigger almalinux-vs-rockylinux-oracle-linux-9 workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: centminmod/centminmod-workflows
          event-type: run-almalinux-vs-rockylinux-oraclelinux-9-workflow-13100stable

      - name: Trigger almalinux-vs-rockylinux-oracle-linux-8-system-openssl workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: centminmod/centminmod-workflows
          event-type: run-almalinux-vs-rockylinux-oraclelinux-8-workflow-system-openssl-13100stable

      - name: Trigger almalinux-vs-rockylinux-oracle-linux-8-openssl30 workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: centminmod/centminmod-workflows
          event-type: run-almalinux-vs-rockylinux-oraclelinux-8-workflow-openssl30-13100stable
          
      - name: Trigger almalinux-vs-rockylinux-oracle-linux-9-openssl30 workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: centminmod/centminmod-workflows
          event-type: run-almalinux-vs-rockylinux-oraclelinux-9-workflow-openssl30-13100stable

      - name: Trigger almalinux-vs-rockylinux-oracle-linux-8-openssl31 workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: centminmod/centminmod-workflows
          event-type: run-almalinux-vs-rockylinux-oraclelinux-8-workflow-openssl31-13100stable
          
      - name: Trigger almalinux-vs-rockylinux-oracle-linux-9-openssl31 workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: centminmod/centminmod-workflows
          event-type: run-almalinux-vs-rockylinux-oraclelinux-9-workflow-openssl31-13100stable

      - name: Trigger almalinux-vs-rockylinux-oracle-linux-8 PGO workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: centminmod/centminmod-workflows
          event-type: run-almalinux-vs-rockylinux-oraclelinux-8-workflow-pgo-13100stable
          
      - name: Trigger almalinux-vs-rockylinux-oracle-linux-9 PGO workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: centminmod/centminmod-workflows
          event-type: run-almalinux-vs-rockylinux-oraclelinux-9-workflow-pgo-13100stable